### 
//Get All Products
GET http://localhost:5000/product/


### 
//Get Single Product
GET http://localhost:5000/product/c3772418-1183-426c-9b68-ce833bd23f30


### 
//Create Product (Admin Only)
POST http://localhost:5000/product
Content-Type: application/json

{
  "name": "Buahahahaha",
  "price": 10000
}


### 
//Edit Product (Admin Only)
PATCH http://localhost:5000/product/c3772418-1183-426c-9b68-ce833bd23f30
Content-Type: application/json

{
  "name": "Buah Kuldi",
  "price": 192309213213
}

### 
//Delete Product (Admin Only)
DELETE http://localhost:5000/product/c3772418-1183-426c-9b68-ce833bd23f30